### ISSUE TITLE
Analytics Revisions

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-map#333]
# Details

As pointed out in slack:

> “0.44% of sessions led to a “share.” Of these, 56.15% were a click of the “embed” link.”
While low, I think this is nevertheless inflated because what we track here is pressing the <> embed button. To get more accurate numbers, it makes more sense to me to assign the event to clicks of the “copy code” buttons. I suspect a lot of what we’re seeing here would be “curiosity clicks” (not a bad thing to know in itself, though).

# Next steps
- [ ] do not track the "embed" and "link" buttons as a share, instead use the "copy" button to track the share for these two options

@james-minton any other analytics revisions / requests on the explorer?

**Comment by james-minton** [comment]
@Lane no more I can think of for the Explorer, but thinking "scroll depth" tracking on Discoveries in the container site might be good, so we can see how many people finish the articles?

**Comment by Lane** [comment]
@james-minton for sure, i've added this to the analytics revisions on the container site repo: https://github.com/Hyperobjekt/seda-site/issues/44

**Comment by james-minton** [comment]
@Lane I vaguely remember us deciding on not tracking data downloads because the university does that themselves. But now I can’t think of a reason not to track them ourselves too, to wrap everything into one package. 

Does adding CTA tracking to the downloads page make sense? 

And could we also filter out clicks on navigation items on that page (e.g. the tabs between different versions)? If not, that’s easy enough to manually do in GA. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lane** [comment]
@james-minton yep, that's doable.  this is the explorer repository though, analytics requests for the container site should go in that repo: https://github.com/Hyperobjekt/seda-site/issues/44

**Comment by amygroshek** [comment]
Merged into production.
