### ISSUE TITLE
Zoom in on chart view

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#461]
Feedback from client: The map zooms in on the selected location, but it’s not as obvious in the chart view - there are many bubbles so unless I happen to click on the right bubble by chance, it’ll take effort to find it

To do: can we zoom in more in chart view?

**Comment by Lane** [comment]
unfortunately we don't have "zoom" functionality with the chart, and it would be a pretty big lift to implement something like that.

in order to address the difficulty of finding a location in the mass of bubbles, we have done the following:  
- any selected locations (via map or search) are added to the "selected locations", which highlights them in the map and on the chart:
![image](https://user-images.githubusercontent.com/21034/104966984-0f815500-5997-11eb-926b-f78443d4d8d2.png)

- if interested on focusing within a certain range of bubbles on the chart, the filters can be adjusted to focus on a specific area which has a similar effect as "zooming"

![image](https://user-images.githubusercontent.com/21034/104967030-3c356c80-5997-11eb-95aa-1aae4ee825f9.png)

> Noticing when a place is selected via search it is not getting added to "selected places", this is a bug and will add an issue for that.

**Comment by laurendoone** [comment]
Got it, will explain this to the client. 

Regarding "Noticing when a place is selected via search it is not getting added to "selected places", this is a bug and will add an issue for that." - client also noticed that. I'll create an issue.

**Comment by laurendoone** [comment]
@Lane just tested by searching for "san diego county" but I don't see any orange outline in the chart view indicating which one is San Diego. Am i doing this wrong?
![Screen Shot 2021-01-18 at 2 24 57 PM](https://user-images.githubusercontent.com/76966798/104967742-f8dbfd80-5998-11eb-9b75-51fead787bed.png)

**Comment by Lane** [comment]
@laurendoone  fixed the issue where the location doesn't get highlighted after selecting in search.  https://dev.edopportunity.org/explorer/

is this issue good to close?

**Comment by laurendoone** [comment]
yep looks good to me! can close it
