### ISSUE TITLE
Add filter to schools

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-map#502]
Question from Sean: when filtering schools -- how do i select only charter schools or only magnet? seems there's no way to turn off regular schools; there should be a "regular" school option (that includes all schools other than charter and magnet)

Is this something he's able to do? Or do we need to add a new filter option?

**Comment by Lane** [comment]
right, this makes sense.  the current functionality does not allow viewing _only_ magnet or _only_ charter schools.  in order to fix this, i think we need to switch these from non-exclusive flags to exclusive flags.

filters can be added as "exclusive" but adding their identifiers to the [EXCLUSIVE_FLAGS array](https://github.com/Hyperobjekt/seda-map/blob/b7651fcc4bacce317bcfd965ff6925e20d388340/src/modules/explorer/app/constants/flags.js#L14):

e.g. charter and magnet added to exclusive flags:
```
export const EXCLUSIVE_FLAGS = ['ch', 'mg']
```

in addition to this, exclusive flags should be switched from rendering with checkboxes, to rendering with [radio button](https://material-ui.com/components/radio-buttons/), as only one can be active at a time.  The exclusive flags section should look as follows:

Show schools by type:
- ◉ All schools
- ⊙ Magnet
- ⊙ Charter
- ⊙ Bureau of Indian Education (if on the embargoed site)

non-exclusive flags should remain as checkboxes.

**Comment by laurendoone** [comment]
@touchRED @Lane client feedback from staging review: Right now I can only select either "all, charter, or magnet," can we make those check boxes? Currently I can see all charters or all magnet, but I can't select only regular schools. I think the three checkboxes should be" regular (or traditional?), charter, magnet

**Comment by Lane** [comment]
@touchRED this will require some reworking of how we filter flags, given we do not have any indicators in the data for what is a "regular school".

the easiest solution might be to shape the data when it loads to see if it has the `mg`, `ch`, or `bie` flag, and if not then add a `reg` flag to mark it as a regular school.

after that, switch charter, magnet, and BIE (`ch`, `mg`, `bie`) back to "non-exclusive filters" and add an additional non-exclusive filter for `reg`.
